server:
  port: 9527
  
spring:
  application:
    name: stockmarket-zuul-gateway
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
    
zuul:
  prefix: /fsb
  #ignored-services: stockmarket-provider
  ignored-services: "*"
  routes:
    myprovider.serviceId: stockmarket-provider
    myprovider.path: /myprovider/**
    
info:
  app.name: fsb-stockmarket
  company.name: www.ibm.com
  build.artifactId: stockmarket-zuul-gateway-9527
  build.version: 0.0.1-SNAPSHOT
  